version: "3.9"
services:
  komobox:
    build: ./komobox
    environment:
      ENDPOINT: http://minikom:8080/event
    depends_on:
      - minikom

  minikom:
    build: ./minikom
    environment:
      - DB_HOST=postgres
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:13.1
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432